matrix:
  include:
    - os: linux
      dist: xenial
      language: ruby
      cache: bundler
      rvm:
        - 2.3.8
        - 2.4.5
        - 2.5.4
        - 2.6.2
      script:
        - bundle exec docker version
        - bundle exec kitchen --version
        - bundle exec rake spec
        - bundle exec kitchen test -d always
    - os: windows
      language: bash
      install:
        - choco install msys2
      script:
        - export KITCHEN_LOCAL_YAML=".kitchen.windows.yml"
        - ruby -v
        - gem install bundler
        - bundle install --force
        - bundle exec docker version
        - bundle exec kitchen --version
        - bundle exec rake spec
        - bundle exec kitchen test -d always

services:
- docker
