matrix:
  include:
    - os: linux
      rvm:
        - 2.4.5
        - 2.5.4
        - 2.6.2
      dist: xenial
      language: ruby
      cache: bundler
      script:
        - bundle exec docker version
        - bundle exec kitchen --version
        - bundle exec rake spec
        - bundle exec kitchen test -d always
    - os: windows
      language: bash
      env:
        YARN_GPG=no
      install:
        - choco install mingw
        - choco install msys2
        - ridk.cmd exec pacman -S --noconfirm --needed base-devel mingw-w64-x86_64-toolchain
      script:
        - powershell -ExecutionPolicy Bypass -NoLogo -File docker.ps1
        - export KITCHEN_YAML=.kitchen.windows.yml
        - export PATH=$PATH:/c/opscode/chef/embedded/bin
        - printenv
        - ruby -v
        - gem install bundler
        - bundle install
        - bundle exec docker version
        - bundle exec kitchen --version
        - bundle exec rake spec
        - travis_wait 30 bundle exec kitchen test -d always

services:
- docker
