matrix:
  include:
    - os: linux
      dist: xenial
      language: ruby
      cache: bundler
      rvm:
        - 2.3.8
        - 2.4.5
        - 2.5.4
        - 2.6.2
      script:
        - bundle exec docker version
        - bundle exec kitchen --version
        - bundle exec rake spec
        - bundle exec kitchen test -d always
    - os: windows
      language: bash
      script:
        - export DOCKER_HOST="tcp://0.0.0.0:2375"
        - export KITCHEN_LOCAL_YAML=".kitchen.windows.yml"
        - ruby -v
        - C:\opscode\chef\embedded\bin\bundle exec docker version
        - C:\opscode\chef\embedded\bin\bundle exec kitchen --version
        - C:\opscode\chef\embedded\bin\bundle exec rake spec
        - C:\opscode\chef\embedded\bin\bundle exec kitchen test -d always

services:
- docker
