matrix:
  include:
    - os: linux
      dist: xenial
      language: ruby
      cache: bundler
      script:
        - bundle exec docker version
        - bundle exec kitchen --version
        - bundle exec rake spec
        - bundle exec kitchen test -d always
    - os: windows
      language: ruby
      script:
        - export KITCHEN_LOCAL_YAML=".kitchen.windows.yml"
        - bundle exec docker version
        - bundle exec kitchen --version
        - bundle exec rake spec
        - bundle exec kitchen test -d always

rvm:
- 2.3.8
- 2.4.5
- 2.5.4
- 2.6.2

services:
- docker
